/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

/**
 *
 * @author Lenovo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Reservasi = new javax.swing.JButton();
        Pegawai = new javax.swing.JButton();
        Uang = new javax.swing.JButton();
        bgmenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Bright", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 140, 60));

        Reservasi.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        Reservasi.setText("RESERVASI");
        Reservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservasiActionPerformed(evt);
            }
        });
        getContentPane().add(Reservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 50));

        Pegawai.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        Pegawai.setText("PEGAWAI");
        Pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(Pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, 50));

        Uang.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        Uang.setText("LAPORAN KEUANGAN");
        Uang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UangActionPerformed(evt);
            }
        });
        getContentPane().add(Uang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 250, 50));

        bgmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/menu1.jpeg"))); // NOI18N
        bgmenu.setText("jLabel1");
        getContentPane().add(bgmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 466, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservasiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ReservasiActionPerformed

    private void PegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PegawaiActionPerformed

    private void UangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pegawai;
    private javax.swing.JButton Reservasi;
    private javax.swing.JButton Uang;
    private javax.swing.JLabel bgmenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
